@startuml
!theme plain
autonumber

actor "Logistics Operator" as Actor
participant "<<system (C4)>>\nPort System" as System

Actor -> System : 1: create/update/deactivate/search staff members
activate System
System --> Actor : 1.1: staff member data / confirmation
deactivate System

@enduml