@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
hide circle
hide methods

title US221 - Add a Customer Representative - Domain Model

class Customer {
    vatNumber
    name
    address
    email
    phoneNumber
    type
    status
}

class CustomerRepresentative {
    name
    email
    phoneNumber
    position
    status
}

class SystemUser {
    name
    email
    password
    phone
    active
}

class Role {
    name
}

Customer "1" - "0..1" CustomerRepresentative : representative >
CustomerRepresentative "1" - "1" SystemUser : is >
SystemUser "1" - "1..*" Role : has >

@enduml
