@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title US221 - Add a Customer Representative

actor "CRM Collaborator" as CRM
participant ":RegisterCustomerRepresentativeUI" as UI
participant ":RegisterCustomerRepresentativeController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "customerRepository:\nCustomerRepository" as customerRepository
participant "systemUserRepository:\nSystemUserRepository" as systemUserRepository
participant "customerRepresentativeRepository:\nCustomerRepresentativeRepository" as customerRepresentativeRepository

activate CRM

CRM -> UI : asks to register a new customer representative
activate UI
UI --> CRM : requests input (customer VAT, name, email, phone, position)
deactivate UI

CRM -> UI : types requested data
activate UI

UI -> CTRL : registerRepresentative(customerVAT, name, email, phone, position)
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton

CTRL -> PLAT : customerRepository()
activate PLAT
PLAT --> CTRL : customerRepository
deactivate PLAT

CTRL -> customerRepository : findByVATNumber(customerVAT)
activate customerRepository
customerRepository --> CTRL : Customer
deactivate customerRepository

CTRL -> PLAT : systemUserRepository()
activate PLAT
PLAT --> CTRL : systemUserRepository
deactivate PLAT

CTRL -> systemUserRepository : save(SystemUser)
activate systemUserRepository
systemUserRepository --> CTRL : SystemUser
deactivate systemUserRepository

CTRL -> PLAT : customerRepresentativeRepository()
activate PLAT
PLAT --> CTRL : customerRepresentativeRepository
deactivate PLAT

CTRL -> customerRepresentativeRepository : save(CustomerRepresentative)
activate customerRepresentativeRepository
customerRepresentativeRepository --> CTRL : CustomerRepresentative
deactivate customerRepresentativeRepository

CTRL --> UI : status of operation (success/failure)
deactivate CTRL

UI -> UI : displayStatusMessage
activate UI
deactivate UI

UI --> CRM : operation result message
deactivate UI

deactivate CRM

@enduml
