@startuml
!theme plain
autonumber

actor "Shipping Agent Rep." as Actor
participant "<<system (C4)>>\nPort System" as System

Actor -> System : 1: create and submit vessel visit notification
activate System
System --> Actor : 1.1: notification created and submitted
deactivate System

@enduml