@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Product Manager" as PM
participant ":USEI01UI" as UI
participant "SimulationController" as SC
participant "WorkstationRepository" as WR
participant "ItemRepository" as IR

activate UI
activate PM

      PM -> UI : Requests data import

      UI -> UI: Prompt for item file path
      UI -> UI: Prompt for workstation file path


      UI -> SC: loadItemsFromCSV(itemFilePath)
      activate SC
      SC -> IR : setItems(itemList)
      activate IR
      deactivate SC

      UI -> SC : loadMachinesFromCSV(machineFilePath)
      activate SC

      SC -> WR : setWorkstation(machineList)
      deactivate SC
      activate WR

      UI --> PM : Data imported successfully!
      deactivate UI
      deactivate PM

      deactivate IR
      deactivate WR












@enduml