@startuml
!pragma layout smetana
title Port Management Domain Model


' Aggregate: VesselType
package "VesselType" {
    class VesselType <<Root>> <<Entity>> #D1E5F4 {
    }
    class VesselTypeId <<ValueObject>> {}
    class VesselTypeName <<ValueObject>> {}
    class VesselTypeDescription <<ValueObject>> {}
    class VesselTypeCapacity <<ValueObject>> {}
    class VesselTypeDimensions <<ValueObject>>{}

    VesselType "1" *-- "1" VesselTypeId
    VesselType "1" *-- "1" VesselTypeName
    VesselType "1" *-- "1" VesselTypeDescription
    VesselType "1" *-- "1" VesselTypeCapacity
    VesselType "1" *-- "1" VesselTypeDimensions

}

' Aggregate: Vessel
package "Vessel" {
    class Vessel <<Root>> <<Entity>> #D1E5F4 {
        
    }
    class ImoNumber <<ValueObject>> {}
    class Name <<ValueObject>> {}
    class Owner <<ValueObject>> {}

    

    Vessel "1" *-- "1" ImoNumber
    Vessel "1" *-- "1" Name
    Vessel "1" *-- "1" Owner
}

' Aggregate: Dock
package "Dock" {
    class Dock <<Root>> <<Entity>> #D1E5F4 {
    }
    class DockId <<ValueObject>> {}
    class DockName <<ValueObject>> {}
    class DockLocation <<ValueObject>> {}
    class DockCapacity <<ValueObject>> {

    }
    class PhysicalCharacteristics <<ValueObject>> {
        - length
        - depth
        -maxDraft
    }


    Dock "1" *-- "1" DockId
    Dock "1" *-- "1" DockName
    Dock "1" *-- "1" DockLocation
    Dock "1" *-- "1" PhysicalCharacteristics
    Dock "1" *-- "1" DockCapacity
}

' Aggregate: StorageArea
package "StorageArea" {
    class StorageArea <<Root>> <<Entity>> #D1E5F4 {
    }
    class StorageAreaId <<ValueObject>> {}
    class StorageAreaLocation <<ValueObject>> {}
    enum StorageAreaType <<ValueObject>> {
        Yard
        Warehouse
    }
    class StorageCapacity <<ValueObject>> {
    }
    class DockDistance <<ValueObject>> {

    }

    StorageArea "1" *-- "1" StorageAreaId
    StorageArea "1" *-- "1" StorageAreaLocation
    StorageArea "1" *-- "1" StorageAreaType
    StorageArea "1" *-- "1" StorageCapacity
    StorageArea "1" *-- "*" DockDistance
}

' Aggregate: ShippingAgentOrganization
package "ShippingAgentOrganization" {
    class ShippingAgentOrganization <<Root>> <<Entity>> #D1E5F4 {}
    class OrganizationId <<ValueObject>> {}
    class Address <<ValueObject>> {}


    ShippingAgentOrganization "1" *-- "1" OrganizationId
    ShippingAgentOrganization "1" *-- "1" Address
}

' Aggregate: Representative
package "ShippingAgentRepresentative" {
    class ShippingAgentRepresentative <<Root>> <<Entity>> #D1E5F4 {   }
    class RepresentativeId <<ValueObject>> {}
   class citizenId <<ValueObject>> {}
   class RepresentativeName <<ValueObject>> {}
   class RepresentativeEmail <<ValueObject>> {}
    class RepresentativePhone <<ValueObject>> {}

    "ShippingAgentRepresentative" "1" *-- "1" RepresentativeId
    "ShippingAgentRepresentative" "1" *-- "1" citizenId
    "ShippingAgentRepresentative" "1" *-- "1" RepresentativeName
    "ShippingAgentRepresentative" "1" *-- "1" RepresentativeEmail
    "ShippingAgentRepresentative" "1" *-- "1" RepresentativePhone

}

' Aggregate: StaffMember
package "StaffMember" {
    class StaffMember <<Root>> <<Entity>> #D1E5F4 {
    }
    class MecanographicNumber <<ValueObject>> {}
    enum StaffStatus <<ValueObject>> {
        Available
        Unavailable
    }
    class OperationalWindow <<ValueObject>> {}
    class StaffName <<ValueObject>> {}
    class StaffEmail <<ValueObject>> {}
    class StaffPhone <<ValueObject>> {}
    enum StaffRole <<ValueObject>> {
        PortAuthorityOfficer
        LogisticsOperator
        Admin
    }


    StaffMember "1" *-- "1" MecanographicNumber
    StaffMember "1" *-- "1" StaffStatus
    StaffMember "1" *-- "1" OperationalWindow
    StaffMember "1" *-- "1" StaffName
    StaffMember "1" *-- "1" StaffEmail
    StaffMember "1" *-- "1" StaffPhone
    StaffMember "1" *-- "1" StaffRole


}

' Aggregate: PhysicalResource
package "PhysicalResource" {
    class PhysicalResource <<Root>> <<Entity>> #D1E5F4 {

    }
    class ResourceCode <<ValueObject>> {}
    enum ResourceStatus <<ValueObject>> {
        Active
        Inactive
        UnderMaintenance
    }
    class OperationalCapacity <<ValueObject>> {}
    class SetupTime <<ValueObject>> {}


    PhysicalResource "1" *-- "1" ResourceCode
    PhysicalResource "1" *-- "1" ResourceStatus
    PhysicalResource "1" *-- "1" OperationalCapacity
    PhysicalResource "1" *-- "1" SetupTime
}

' Aggregate: Qualification
package "Qualification" {
    class Qualification <<Root>> <<Entity>> #D1E5F4 {

    }
    class QualificationCode <<ValueObject>> {}
    class QualificationName <<ValueObject>> {}
    class QualificationDescription <<ValueObject>> {}

    Qualification "1" *-- "1" QualificationCode
    Qualification "1" *-- "1" QualificationName
    Qualification "1" *-- "1" QualificationDescription
}

' Aggregate: VesselVisitNotification
package "VesselVisitNotification" {
    class VesselVisitNotification <<Root>> <<Entity>> #D1E5F4 {

    }
    class NotificationId <<ValueObject>> {}
    enum NotificationStatus <<ValueObject>> {
        InProgress
        Submitted
        Approved
        Rejected
    }
    class CargoManifest <<Entity>> {}
    class Container <<Entity>> {

    }
    class ContainerCode <<ValueObject>> {}
    class CrewMember <<Entity>> {

    }
    class CrewMemberId <<ValueObject>> {}

    class DecisionLogEntry <<Entity>> {

    }

    VesselVisitNotification "1" *-- "1" NotificationId
    VesselVisitNotification "1" *-- "1" NotificationStatus
    VesselVisitNotification "1" *-- "1" CargoManifest
    VesselVisitNotification "1" *-- "*" CrewMember
    CrewMember "1" *-- "1" CrewMemberId

    VesselVisitNotification "1" *-- "*" DecisionLogEntry
    CargoManifest "1" *-- "*" Container
    Container "1" *-- "1" ContainerCode
}

class NotificationManagementService <<Service>>{
    submitNotification()
    approveNotification()
    rejectNotification()
    updateNotification()
}


' --- Inter-Aggregate Relationships ---
' These are references by ID, not direct object composition.

Vessel.Vessel "1" --> "1" VesselType.VesselType : "references"
Dock.Dock "1" ----> "*" VesselType.VesselType : "allows"
StorageArea.StorageArea "1" ---> "*" Dock.Dock : "serves"
ShippingAgentRepresentative.ShippingAgentRepresentative "1" ---> "1" ShippingAgentOrganization.ShippingAgentOrganization : "works for"

StaffMember.StaffMember "1" ---> "*" Qualification.Qualification : "has"
PhysicalResource.PhysicalResource "1" --> "*" Qualification.Qualification : "requires"

VesselVisitNotification.VesselVisitNotification "1" --> "1" Vessel.Vessel : "is for"
VesselVisitNotification.VesselVisitNotification "1" --> "1" ShippingAgentRepresentative.ShippingAgentRepresentative : "submitted by"
VesselVisitNotification.VesselVisitNotification "1" -> "0..1" Dock.Dock : "assigned to"
DockDistance "1" --> "1" Dock.Dock : "to"

NotificationManagementService "1" ..> "1" VesselVisitNotification.VesselVisitNotification : "manages"
"StaffMember" "1" ..> "1" NotificationManagementService : "uses"
NotificationManagementService "1" ..> "1" Dock.Dock : "checks"

@enduml