@startuml
!theme plain
autonumber

actor "User" as User
participant "<<system (C4)>>\nPort System" as AIT

User -> AIT : 1: authenticate with credentials
activate AIT
AIT --> User : 1.1: authentication token provided
deactivate AIT

@enduml
