export type SchedulingAlgorithm = 'optimal' | 'heuristic' | 'multicrane' | 'genetic' | 'automatic' | 'rebalancing';

export type CraneMode = 'single' | 'multiple';

export interface GeneticAlgorithmParams {
    populationSize: number;
    generations: number;
    mutationRate: number;
    desiredTimeSeconds: number;
    craneMode: CraneMode;
}

// US 4.3.3 - Rebalancing algorithm parameters
export interface RebalancingAlgorithmParams {
    expectedDepartureDelaysWeight: number;
    dockCapacityAndCongestionWeight: number;
    craneAvailabilityWeight: number;
    maxIterations: number;
    desiredTimeSeconds: number;
    enforceVesselAndDockConstraints: boolean;
    variant: 'simulatedAnnealing' | 'tabuSearch' | string;
}

export interface DailyScheduleRequest {
    date: string; // ISO date string (YYYY-MM-DD)
    algorithm?: SchedulingAlgorithm; // Algorithm to use (default: optimal)
    geneticParams?: GeneticAlgorithmParams; // Parameters for genetic algorithm
    // US 4.3.3 - Parameters for rebalancing algorithm (used when algorithm === 'rebalancing')
    rebalancingParams?: RebalancingAlgorithmParams;
}

export interface ScheduledTask {
    vesselVisitId: string;
    resourceId: string; // The crane
    staffId: string;    // The operator
    
    // Display names (for UI - user-friendly names instead of IDs)
    vesselImo: string;
    vesselVisitBusinessId: string;
    dockName: string;
    resourceKind: string;
    staffShortName: string;
    
    startTime: string;  // ISO datetime string
    endTime: string;    // ISO datetime string
    
    // Loading and Unloading times (in hours)
    loadingTime: number;
    unloadingTime: number;

    // Detailed sub-operations (generated by backend)
    subOperations?: SubOperation[];
}

export interface SubOperation {
    operationId: string;
    type: string;
    name: string;
    plannedStartTime: string;
    plannedEndTime: string;
}

export interface DailyScheduleResponse {
    date: string; // ISO date string
    scheduledTasks: ScheduledTask[];
    totalDelay: number;
    warnings: string[];
    executionTimeMs: number;
    algorithmUsed?: string; // The actual algorithm used (useful when "automatic" is selected)
}

export interface VesselVisitNotification {
    id: string;
    businessId: string;
    vesselImo: string;
    estimatedArrival: string;
    estimatedDeparture: string;
    assignedDockId?: string;
    assignedDockName?: string;
    status: string;
}

export interface ExistingPlanSummary {
    planId: string;
    algorithm: string;
    scheduledTasksCount: number;
    createdAt: string;
}

export interface MissingPlansResponse {
    missingVVNs: VesselVisitNotification[];
    existingPlans: ExistingPlanSummary[];
}

// US 4.3.3 - Rebalancing proposal response from Planning API
export interface RebalancingProposal {
    proposalId: string;
    date: string;
    algorithm: 'rebalancing';
    baselineTasks: ScheduledTask[];
    proposedTasks: ScheduledTask[];
    totalDelayBaseline: number;
    totalDelayProposed: number;
    warnings: string[];
    // Convenience metric that backend may include (optional): improvement in minutes
    improvementMinutes?: number;
}

// US 4.3.3 - Confirm rebalancing proposal request
export interface RebalancingConfirmRequest {
    proposalId: string;
    officerId: string;
    officerName?: string;
    planId?: string;
    comments?: string;
}
