// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortProject.Api.Models;

#nullable disable

namespace PortProject.Api.Migrations
{
    [DbContext(typeof(PortProjectContext))]
    [Migration("20251016083733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PortProject.Api.Domain.DockAggregate.Dock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Docks");
                });

            modelBuilder.Entity("PortProject.Api.Domain.QualificationAggregate.Qualification", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.ShippingAgentOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeName")
                        .HasColumnType("TEXT")
                        .HasColumnName("AlternativeName");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LegalName");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TaxNumber");

                    b.HasKey("Id");

                    b.ToTable("ShippingAgentOrganizations");
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentRepresentativeAggregate.ShippingAgentRepresentative", b =>
                {
                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CitizenId");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativeEmail");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativeName");

                    b.Property<string>("RepresentativeNationality")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativeNationality");

                    b.Property<string>("RepresentativePhone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativePhone");

                    b.HasKey("RepresentativeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ShippingAgentRepresentatives");
                });

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.Property<string>("MecanographicNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MecanographicNumber");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("PortProject.Api.Domain.StorageAggregate.StorageArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselAggregate.Vessel", b =>
                {
                    b.Property<string>("ImoNumber")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("IMO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VesselTypeId");

                    b.HasKey("ImoNumber");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.Property<string>("QualificationsCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffMemberMecanographicNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationsCode", "StaffMemberMecanographicNumber");

                    b.HasIndex("StaffMemberMecanographicNumber");

                    b.ToTable("StaffMemberQualification", (string)null);
                });

            modelBuilder.Entity("src.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("PortProject.Api.Domain.DockAggregate.Dock", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.DockLocation", "Location", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationSection");

                            b1.Property<string>("Zone")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationZone");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.DockName", "Name", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DockName");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.NumberOfSTSCranes", "STSCranes", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("NumberOfSTSCranes");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.PhysicalCharacteristics", "Characteristics", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("DepthInMeters")
                                .HasColumnType("REAL")
                                .HasColumnName("Depth");

                            b1.Property<double>("LengthInMeters")
                                .HasColumnType("REAL")
                                .HasColumnName("Length");

                            b1.Property<double>("MaxDraftInMeters")
                                .HasColumnType("REAL")
                                .HasColumnName("MaxDraft");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsMany("src.Domain.VesselTypeAggregate.VesselTypeId", "AllowedVesselTypes", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("VesselTypeId");

                            b1.HasKey("DockId", "Value");

                            b1.ToTable("DockAllowedVesselTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.Navigation("AllowedVesselTypes");

                    b.Navigation("Characteristics")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("STSCranes")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.ShippingAgentOrganization", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ShippingAgentOrganizationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Street");

                            b1.HasKey("ShippingAgentOrganizationId");

                            b1.ToTable("ShippingAgentOrganizations");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentOrganizationId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentRepresentativeAggregate.ShippingAgentRepresentative", b =>
                {
                    b.HasOne("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.ShippingAgentOrganization", null)
                        .WithMany("Representatives")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("WorkingDays")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.Navigation("ContactDetails")
                        .IsRequired();

                    b.Navigation("OperationalWindow")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.StorageAggregate.StorageArea", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.StorageAggregate.StorageAreaLocation", "Location", b1 =>
                        {
                            b1.Property<int>("StorageAreaId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("X")
                                .HasColumnType("REAL")
                                .HasColumnName("X");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL")
                                .HasColumnName("Y");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StorageAggregate.StorageCapacity", "Capacity", b1 =>
                        {
                            b1.Property<int>("StorageAreaId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselAggregate.Vessel", b =>
                {
                    b.HasOne("src.Domain.VesselTypeAggregate.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PortProject.Api.Domain.VesselAggregate.VesselOperator", "Operator", b1 =>
                        {
                            b1.Property<string>("VesselImoNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("OperatorName");

                            b1.HasKey("VesselImoNumber");

                            b1.ToTable("Vessels");

                            b1.WithOwner()
                                .HasForeignKey("VesselImoNumber");
                        });

                    b.Navigation("Operator")
                        .IsRequired();
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.HasOne("PortProject.Api.Domain.QualificationAggregate.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberMecanographicNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeCapacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDescription", "Description", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDimensions", "OperationalConstraints", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxBays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxBays");

                            b1.Property<int>("MaxRows")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxRows");

                            b1.Property<int>("MaxTiers")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeName", "Name", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("VesselTypeId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OperationalConstraints")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.ShippingAgentOrganization", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
