// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortProject.Api.Models;

#nullable disable

namespace PortProject.Api.Migrations
{
    [DbContext(typeof(PortProjectContext))]
    [Migration("20251007151022_renameBays")]
    partial class renameBays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("src.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("src.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeCapacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDescription", "Description", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDimensions", "OperationalConstraints", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Bays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Bays");

                            b1.Property<int>("Rows")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rows");

                            b1.Property<int>("Tiers")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Tiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeName", "Name", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OperationalConstraints")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
