// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortProject.Api.Models;

#nullable disable

namespace PortProject.Api.Migrations
{
    [DbContext(typeof(PortProjectContext))]
    [Migration("20251024130402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PortProject.Api.Domain.DockAggregate.Dock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Docks");
                });

            modelBuilder.Entity("PortProject.Api.Domain.QualificationAggregate.Qualification", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("ResourceCode");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("PortProject.Api.Domain.ResourceAggregate.Resource", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<string>("AssignedArea")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedArea");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("_qualificationRequirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("QualificationRequirements");

                    b.HasKey("Code");

                    b.ToTable("Resources", (string)null);
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.ShippingAgentOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeName")
                        .HasColumnType("TEXT")
                        .HasColumnName("AlternativeName");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LegalName");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TaxNumber");

                    b.HasKey("Id");

                    b.ToTable("ShippingAgentOrganizations");
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentRepresentativeAggregate.ShippingAgentRepresentative", b =>
                {
                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CitizenId");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("OrganizationId");

                    b.Property<string>("RepresentativeEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativeEmail");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativeName");

                    b.Property<string>("RepresentativeNationality")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativeNationality");

                    b.Property<string>("RepresentativePhone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RepresentativePhone");

                    b.HasKey("RepresentativeId");

                    b.ToTable("ShippingAgentRepresentatives");
                });

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.Property<string>("MecanographicNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MecanographicNumber");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("PortProject.Api.Domain.StorageAggregate.StorageArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselAggregate.Vessel", b =>
                {
                    b.Property<string>("ImoNumber")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("IMO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VesselTypeId");

                    b.HasKey("ImoNumber");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselVisitNotificationAggregate.VesselVisitNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedDockId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDockId");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVisitNotifications");
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.Property<string>("QualificationsCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffMemberMecanographicNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationsCode", "StaffMemberMecanographicNumber");

                    b.HasIndex("StaffMemberMecanographicNumber");

                    b.ToTable("StaffMemberQualification", (string)null);
                });

            modelBuilder.Entity("PortProject.Api.Domain.DockAggregate.Dock", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.DockLocation", "Location", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationSection");

                            b1.Property<string>("Zone")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationZone");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.DockName", "Name", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DockName");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.NumberOfSTSCranes", "STSCranes", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("NumberOfSTSCranes");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.DockAggregate.PhysicalCharacteristics", "Characteristics", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("DepthInMeters")
                                .HasColumnType("REAL")
                                .HasColumnName("Depth");

                            b1.Property<double>("LengthInMeters")
                                .HasColumnType("REAL")
                                .HasColumnName("Length");

                            b1.Property<double>("MaxDraftInMeters")
                                .HasColumnType("REAL")
                                .HasColumnName("MaxDraft");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsMany("src.Domain.VesselTypeAggregate.VesselTypeId", "AllowedVesselTypes", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("VesselTypeId");

                            b1.HasKey("DockId", "Value");

                            b1.ToTable("DockAllowedVesselTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.Navigation("AllowedVesselTypes");

                    b.Navigation("Characteristics")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("STSCranes")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.QualificationAggregate.Qualification", b =>
                {
                    b.HasOne("PortProject.Api.Domain.ResourceAggregate.Resource", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("ResourceCode");
                });

            modelBuilder.Entity("PortProject.Api.Domain.ResourceAggregate.Resource", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.ResourceAggregate.ResourceDescription", "Description", b1 =>
                        {
                            b1.Property<string>("ResourceCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("ResourceCode");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceCode");
                        });

                    b.OwnsOne("PortProject.Api.Domain.ResourceAggregate.ResourceOperationalCapacity", "OperationalCapacity", b1 =>
                        {
                            b1.Property<string>("ResourceCode")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("AverageContainersPerHour")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AvgContainersPerHour");

                            b1.Property<double?>("AverageSpeedKmh")
                                .HasColumnType("REAL")
                                .HasColumnName("AverageSpeedKmh");

                            b1.Property<int?>("ContainersPerTrip")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ContainersPerTrip");

                            b1.Property<double?>("GenericValue")
                                .HasColumnType("REAL")
                                .HasColumnName("CapacityValue");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CapacityKind");

                            b1.Property<string>("Unit")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("CapacityUnit");

                            b1.HasKey("ResourceCode");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceCode");
                        });

                    b.OwnsOne("PortProject.Api.Domain.ResourceAggregate.ResourceOperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("ResourceCode")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalEnd");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalStart");

                            b1.HasKey("ResourceCode");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceCode");
                        });

                    b.OwnsOne("PortProject.Api.Domain.ResourceAggregate.ResourceSetupTime", "SetupTime", b1 =>
                        {
                            b1.Property<string>("ResourceCode")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Minutes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SetupTimeMinutes");

                            b1.HasKey("ResourceCode");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceCode");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("OperationalCapacity")
                        .IsRequired();

                    b.Navigation("OperationalWindow")
                        .IsRequired();

                    b.Navigation("SetupTime")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.ShippingAgentOrganization", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.ShippingAgentOrganizationAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ShippingAgentOrganizationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Street");

                            b1.HasKey("ShippingAgentOrganizationId");

                            b1.ToTable("ShippingAgentOrganizations");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentOrganizationId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("WorkingDays")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.Navigation("ContactDetails")
                        .IsRequired();

                    b.Navigation("OperationalWindow")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.StorageAggregate.StorageArea", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.StorageAggregate.StorageAreaLocation", "Location", b1 =>
                        {
                            b1.Property<int>("StorageAreaId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("X")
                                .HasColumnType("REAL")
                                .HasColumnName("X");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL")
                                .HasColumnName("Y");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StorageAggregate.StorageCapacity", "Capacity", b1 =>
                        {
                            b1.Property<int>("StorageAreaId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselAggregate.Vessel", b =>
                {
                    b.HasOne("PortProject.Api.Domain.VesselTypeAggregate.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PortProject.Api.Domain.VesselAggregate.VesselOperator", "Operator", b1 =>
                        {
                            b1.Property<string>("VesselImoNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("OperatorName");

                            b1.HasKey("VesselImoNumber");

                            b1.ToTable("Vessels");

                            b1.WithOwner()
                                .HasForeignKey("VesselImoNumber");
                        });

                    b.Navigation("Operator")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeCapacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDescription", "Description", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDimensions", "OperationalConstraints", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxBays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxBays");

                            b1.Property<int>("MaxRows")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxRows");

                            b1.Property<int>("MaxTiers")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeName", "Name", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("VesselTypeId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OperationalConstraints")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselVisitNotificationAggregate.VesselVisitNotification", b =>
                {
                    b.HasOne("PortProject.Api.Domain.DockAggregate.Dock", null)
                        .WithMany()
                        .HasForeignKey("AssignedDockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PortProject.Api.Domain.ShippingAgentRepresentativeAggregate.ShippingAgentRepresentative", null)
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortProject.Api.Domain.VesselAggregate.Vessel", null)
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PortProject.Api.Domain.VesselVisitNotificationAggregate.Cargo", "Cargo", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Weight")
                                .HasColumnType("REAL");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");

                            b1.OwnsMany("PortProject.Api.Domain.VesselVisitNotificationAggregate.Container", "Containers", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ContainerCode");

                                    b2.Property<string>("Position")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid?>("VvnId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("VvnId");

                                    b2.ToTable("Containers", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("VvnId");
                                });

                            b1.Navigation("Containers");
                        });

                    b.OwnsOne("PortProject.Api.Domain.VesselVisitNotificationAggregate.ETA", "EstimatedArrival", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("ETA");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.VesselVisitNotificationAggregate.ETD", "EstimatedDeparture", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("ETD");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsMany("PortProject.Api.Domain.VesselVisitNotificationAggregate.CrewMember", "CrewMembers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsSafetyOfficer")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("VvnId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("VvnId");

                            b1.ToTable("CrewMembers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VvnId");
                        });

                    b.OwnsMany("PortProject.Api.Domain.VesselVisitNotificationAggregate.DecisionLogEntry", "DecisionLog", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OfficerId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Reason")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("VvnId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("VvnId");

                            b1.ToTable("DecisionLogEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VvnId");
                        });

                    b.Navigation("Cargo")
                        .IsRequired();

                    b.Navigation("CrewMembers");

                    b.Navigation("DecisionLog");

                    b.Navigation("EstimatedArrival")
                        .IsRequired();

                    b.Navigation("EstimatedDeparture")
                        .IsRequired();
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.HasOne("PortProject.Api.Domain.QualificationAggregate.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberMecanographicNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.ResourceAggregate.Resource", b =>
                {
                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
