// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortProject.Api.Models;

#nullable disable

namespace PortProject.Api.Migrations
{
    [DbContext(typeof(PortProjectContext))]
    partial class PortProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.Property<string>("MecanographicNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MecanographicNumber");

                    b.ToTable("StaffMembers", (string)null);
                });

            modelBuilder.Entity("PortProject.Api.Domain.StorageAggregate.StorageArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas", (string)null);
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselAggregate.Vessel", b =>
                {
                    b.Property<string>("ImoNumber")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("IMO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VesselTypeId");

                    b.HasKey("ImoNumber");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels", (string)null);
                });

            modelBuilder.Entity("src.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes", (string)null);
                });

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("WorkingDays")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.OwnsMany("PortProject.Api.Domain.QualificationAggregate.QualificationId", "Qualifications", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("QualificationIdValue");

                            b1.HasKey("StaffMemberMecanographicNumber", "Id");

                            b1.ToTable("StaffMemberQualifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.Navigation("ContactDetails")
                        .IsRequired();

                    b.Navigation("OperationalWindow")
                        .IsRequired();

                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("PortProject.Api.Domain.StorageAggregate.StorageArea", b =>
                {
                    b.OwnsOne("PortProject.Api.Domain.StorageAggregate.StorageCapacity", "Capacity", b1 =>
                        {
                            b1.Property<int>("StorageAreaId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StorageAggregate.StorageAreaLocation", "Location", b1 =>
                        {
                            b1.Property<int>("StorageAreaId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("X")
                                .HasColumnType("REAL")
                                .HasColumnName("X");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL")
                                .HasColumnName("Y");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselAggregate.Vessel", b =>
                {
                    b.HasOne("src.Domain.VesselTypeAggregate.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PortProject.Api.Domain.VesselAggregate.VesselOperator", "Operator", b1 =>
                        {
                            b1.Property<string>("VesselImoNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("OperatorName");

                            b1.HasKey("VesselImoNumber");

                            b1.ToTable("Vessels", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VesselImoNumber");
                        });

                    b.Navigation("Operator")
                        .IsRequired();
                });

            modelBuilder.Entity("src.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeCapacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDescription", "Description", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeName", "Name", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("VesselTypeId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VesselTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("src.Domain.VesselTypeAggregate.VesselTypeDimensions", "OperationalConstraints", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxBays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxBays");

                            b1.Property<int>("MaxRows")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxRows");

                            b1.Property<int>("MaxTiers")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OperationalConstraints")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
