// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortProject.Api.Models;

#nullable disable

namespace PortProject.Api.Migrations
{
    [DbContext(typeof(PortProjectContext))]
    partial class PortProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.Property<string>("MecanographicNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MecanographicNumber");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("PortProject.Api.Domain.VesselType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("PortProject.Api.Domain.StaffMemberAggregate.StaffMember", b =>
                {
                    b.OwnsMany("PortProject.Api.Domain.QualificationAggregate.QualificationId", "Qualifications", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("QualificationIdValue");

                            b1.HasKey("StaffMemberMecanographicNumber", "Id");

                            b1.ToTable("StaffMemberQualifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.OwnsOne("PortProject.Api.Domain.StaffMemberAggregate.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("WorkingDays")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.Navigation("ContactDetails")
                        .IsRequired();

                    b.Navigation("OperationalWindow")
                        .IsRequired();

                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
