name: Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Directory Structure
        run: ls -R

      - name: Install Dependencies
        run: dotnet restore ./LEI-SEM5-PI-2025-26-3DL-02.sln --verbosity minimal
      - name: Build Solution
        run: dotnet build ./LEI-SEM5-PI-2025-26-3DL-02.sln --no-restore --verbosity minimal